
/*
 * BLDesignBase
 * ------------------------------
 * A design or module used to group functions and cells
 *
 * IMPORTANT NOTE: DO NOT EDIT THIS FILE, edit bl_design.h instead
 *
 */

#include "bl_design_base.h"


string BLDesignBase::get_name()
{
    return this->name;
}

void BLDesignBase::observe_name(shared_ptr<IBLObserver<string>> observer)
{
    name_observers.push_back( observer );
}

void BLDesignBase::set_name(string value)
{
    this->name = value;
    for ( shared_ptr<IBLObserver<string>> observer : name_observers )
    {
        observer->update( value );
    }
}


list<shared_ptr<BLInstance>> BLDesignBase::get_instances()
{
    return this->instances;
}

void BLDesignBase::observe_instances(shared_ptr<IBLObserver<shared_ptr<BLInstance>>> observer)
{
    instances_observers.push_back( observer );
}


void BLDesignBase::add_instance(shared_ptr<BLInstance> value)
{
    this->instances.push_back( value );
    for ( shared_ptr<IBLObserver<shared_ptr<BLInstance>>> observer : instances_observers )
    {
        observer->update( value );
    }
}

