
/*
 * BLDesignBase
 * ------------------------------
 * A design or module used to group functions and cells
 *
 * IMPORTANT NOTE: DO NOT EDIT THIS FILE, edit bl_design.cpp instead
 *
 */

#pragma once

using namespace std;

#include <memory>
#include "bl_observer.h"
#include <list>
#include <string>
#include <list>
class BLInstance;

class BLDesignBase
{
    
    string name;
    list<shared_ptr<IBLObserver<string>>> name_observers;
    
    list<shared_ptr<BLInstance>> instances;
    list<shared_ptr<IBLObserver<shared_ptr<BLInstance>>>> instances_observers;
    
public:
    
    string get_name();
    void observe_name(shared_ptr<IBLObserver<string>> observer);
    void set_name(string value);
    
    list<shared_ptr<BLInstance>> get_instances();
    void observe_instances(shared_ptr<IBLObserver<shared_ptr<BLInstance>>> observer);
    void add_instance(shared_ptr<BLInstance> value);
    
    

};
