
/*
 * BLPinBase
 * ------------------------------
 * Pin of an instance
 *
 * IMPORTANT NOTE: DO NOT EDIT THIS FILE, edit bl_pin.h instead
 *
 */

#include "bl_pin_base.h"


    string BLPinBase::get_name()
    {
        return this->name;
    }

    void BLPinBase::set_name(string value)
        {
            this->name = value;
        }
    

    string BLPinBase::get_direction()
    {
        return this->direction;
    }

    void BLPinBase::set_direction(string value)
        {
            this->direction = value;
        }
    
