
/*
 * BLPortBase
 * ------------------------------
 * A port of a design
 *
 * IMPORTANT NOTE: DO NOT EDIT THIS FILE, edit bl_port.h instead
 *
 */

#include "bl_port_base.h"


    string BLPortBase::get_name()
    {
        return this->name;
    }

    void BLPortBase::set_name(string value)
        {
            this->name = value;
        }
    

    string BLPortBase::get_direction()
    {
        return this->direction;
    }

    void BLPortBase::set_direction(string value)
        {
            this->direction = value;
        }
    
