
/*
 * BLPinBase
 * ------------------------------
 * Pin of an instance
 *
 * IMPORTANT NOTE: DO NOT EDIT THIS FILE, edit bl_pin.h instead
 *
 */

#include "bl_pin_base.h"


string BLPinBase::get_name()
{
    return this->name;
}

void BLPinBase::observe_name(shared_ptr<IBLObserver<string>> observer)
{
    name_observers.push_back( observer );
}

void BLPinBase::set_name(string value)
{
    this->name = value;
    for ( shared_ptr<IBLObserver<string>> observer : name_observers )
    {
        observer->update( value );
    }
}


string BLPinBase::get_direction()
{
    return this->direction;
}

void BLPinBase::observe_direction(shared_ptr<IBLObserver<string>> observer)
{
    direction_observers.push_back( observer );
}

void BLPinBase::set_direction(string value)
{
    this->direction = value;
    for ( shared_ptr<IBLObserver<string>> observer : direction_observers )
    {
        observer->update( value );
    }
}

